#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Sep 29 23:17:36 2019

@author: drewhogan
"""
import random
"""set up variables"""
N = 10
c = 0

Spinner = [1,2,3,4,-2,-2,-N]

""""while loop"""
while N > 0:
    """pick a random number on the spinner"""
    Spin = random.randrange(0, 7)
    x = Spinner[Spin]
    
    
    """actual gameplay and turn counter"""
    N = N - x 
    c = c + 1
        """make sure N is never larger than 10"""
    if N > 10:
        N = 10
        
    print("On turn  ",c)
    print("You spun a ",x)
    print ("Apples remaining: ",N)
print(N)
print("You won in this many turns:", c)


